python/lsst/verify/metric.py, tests/data/metrics/testing.yaml, tests/test_measurements.py, tests/test_metrics.py
The goal of this refactor is to make MetricSet behave similarly to the SpecificationSet introduced in DM-9559 ( #4 ).
- MetricSet creation API matches SpecificationSet
- Metric uses Name classes internally for IDs
- Metric access from a MetricSet matches how specifications are accessed in SpecificationSet
- Check unit test (with setter and getter properties)
- Add tags to (de)serialization of Metrics
- Implement a `subset` method for MetricSet to get a MetricSet for a certain package and/or tag.
=> DM-9532: Establish MetricSet API and update Metric

python/lsst/verify/__init__.py, python/lsst/verify/job.py, python/lsst/verify/jobmetadata.py, python/lsst/verify/measurement.py, python/lsst/verify/measurementset.py, python/lsst/verify/metaquery.py, python/lsst/verify/spec/base.py, python/lsst/verify/specset.py, tests/test_job.py, tests/test_measurements.py, tests/test_specification_set.py, tests/test_threshold_specification.py
- `Measurement.notes` for measurement-level metadata. All keys here are automatically namespace by the metric name.
- `Job.meta` for Job-level metadata, including measurements. Using a `ChainMap`, one can access measurement metadata through `Job.meta`.
- `SpecificationSet.subset()` can now subset based on metadata. Effectively it provides a new `SpecificationSet` with only the specifications that apply to the Job.
- In Specification YAML files, `provenance_query` is renamed to `metadata_query`. The idea being that metadata is proactively set annotations, which is a potentially different thing than rigorous job provenance.
=> DM-10306: Metadata system and Metadata querying

bin.src/dispatch_verify.py, python/lsst/verify/bin/__init__py, python/lsst/verify/bin/dispatchverify.py, python/lsst/verify/job.py, python/lsst/verify/measurementset.py, python/lsst/verify/metadata/__init__.py, python/lsst/verify/metadata/eupsmanifest.py, python/lsst/verify/metadata/jenkinsci.py, python/lsst/verify/metadata/lsstsw.py, python/lsst/verify/metricset.py, python/lsst/verify/specset.py, python/lsst/verify/squash.py, tests/data/lsstsw/build/manifest.txt, tests/data/lsstsw/etc/repos.yaml, tests/test_eupsmanifest.py, tests/test_job.py, tests/test_lsstsw.py, tests/test_measurementset.py, tests/test_metricset.py, tests/test_specification_set.py, tests/test_squash.py, ups/verify.table
`dispatch_verify.py` acts as an upload client to send verification job JSON fields to SQUASH.
Some features:
- Can take multiple Job JSON files; each is merged
- Metric definitions can be added to a Job, ensuring that units are consistent and normalized to the metric definition before sending to SQUASH.
- Instead of, or in addition to, upload to SQUASH, `dispatch_verify.py` can also save the merged JSON document for later processing or archival. It can also print it out to standard output.
- Using an `--env=jenkins` flag, Jenkins environment information is added to the Job metadata.
- Using an `--lsstsw` flag, lsstsw package information is added to the Job metadata.
- Both CLI flag and environment variable-based configuration is supported. The CLI flags override environment variables.
=> DM-10261: Create dispatch_verify.py CLI for uploading a verification job

python/lsst/verify/blob.py, python/lsst/verify/blobset.py, python/lsst/verify/job.py, python/lsst/verify/jobmetadata.py, python/lsst/verify/jsonmixin.py, python/lsst/verify/measurement.py, python/lsst/verify/measurementset.py, python/lsst/verify/metric.py, python/lsst/verify/metricset.py, python/lsst/verify/report.py, python/lsst/verify/spec/base.py, python/lsst/verify/spec/threshold.py, python/lsst/verify/specset.py, tests/test_metricset.py, tests/test_squash.py
Report class uses astropy tables to tabulate specifications and the pass/fail status of measurements.
Report is specifically meant to be used for creating verification documentation in a Jupyter notebook.
=> DM-10357: Tabulated specification test reports

python/lsst/verify/specset.py
If a specification has a base that can't be resolved, then an exception is thrown in the `resolve_document()` method, indicating that it should be added to a retry pile. But we're also modifying that specification in the `resolve_document()` method. So when we do retry the resolution, the specification may not be in a good state.
Doing a deep copy of the original specification in `resolve_document()` solves all these things.
=> DM-10625: Make a copy of spec when resolving it

ups/verify.table
This change add `pytest_flake8` as an EUPS dependency so that pytest can be used by `sconsUtils` for testing.
****
=> DM-11514: Add pytest_flake8 dependency

.gitignore, python/lsst/verify/metaquery.py, python/lsst/verify/spec/base.py, python/lsst/verify/specset.py, tests/test_specification_set.py
This adds a new `required_meta` argument to `SpecificationSet.subset()`:
```rst
required_metadata : `dict` or `lsst.verify.Metadata`, optional
If supplied, only specifications that have **all** the terms in
``required_metadata`` (and their term values match) are selected.
This is opposite to the logic of the ``meta`` argument where a
specification with an empty metadata query is always selected,
for example.
```
Also adds an 'arg_driven' argument to SpecificationSet.query_metadata and to MetadataQuery.__call__ to enable this query mode rather than the default mode.
Example (run in ipython/notebook):
```
from lsst.verify import SpecificationSet
specs = SpecificationSet.load_metrics_package()
metadata = {'filter_name': 'HSC-R'}
print([str(k) for k in …
```
=> DM-12269: Add SpecificationSet.subset(required_meta=...) mode

python/lsst/verify/measurement.py, tests/test_measurements.py
This implements converting unit-less floats and ints to `Quantities` with unit `dimensionless_unscaled`.  There is a test.
****
=> DM-9534: Coerce floats to Quantities

python/lsst/verify/report.py
DM-12253: this makes the reporting method print a symbol for unmeasured metrics as well as passing and failing metrics.
****
=> Report unmeasured metrics

python/lsst/verify/bin/dispatchverify.py
- In the job JSON document created by dispatch_verify.py the metadata
from the execution enviroment is now stored separately. That makes it
easier to identify and store the metadata required by SQuaSH and
antecipate the support for multiple execution enviroments as being
designed at https://sqr-009.lsst.io/
More information on https://jira.lsstcorp.org/browse/DM-13122
****
=> DM-13122: Separate the execution environment metadata from the other metadata in the JSON document sent to SQuaSH (dispatch_verify.py)

python/lsst/verify/job.py, python/lsst/verify/squash.py
- New methods `get_access_token()` and `make_authorization_header()`
- Fixed default SQUASH API URL
- Since we reimplemented the SQUASH API, we decided that the
default version is 1.0, more information at DM-8836
- Fixed API endpoint name jobs -> job
- squash.post() now accepts status code 200 (OK) as returned by flask-jwt
=> DM-13237: Implement authentication via access token

python/lsst/verify/squash.py
- Upload of large verification jobs ~500M to ~1G to the SQuaSH RESTful API
may take several minutes.
- Allow 202 (Accepted) status code used for long requests.
- Avoid the dump of the body request on error, they can be huge and it
just reproduces the verification job being uploaded.
****
- [ X ] Passes Jenkins CI.
=> DM-13394: Increased default http timeout for requests

tests/test_threshold_specification.py
Doing the string match with a floating point Quantity is fraught — and created an issue for a numpy 1.14 upgrade. This substring matching makes sure the that `ThresholdSpecification.__repr__` is generally providing the right info.
Note we can't test this repr by instantiating the object from the repr string because the Astropy quantity `__repr__` isn't instantiable.
Jenkins run: https://ci.lsst.codes/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/27902/pipeline
=> DM-14302: More lenient ThresholdSpecification repr test

tests/test_specification_set.py
Small change on tests to reflect new name for a specification partials id.
See also: https://github.com/lsst/verify_metrics/pull/12
****
=> [DM-15165] Add new tags for validate_drp metric definition and specifications

.travis.yml
- Removes old travis script to build documentation locally.
- Uses the standard Travis script to run flake8 from the stack package template.
=> DM-16564: Standardize travis.yml file

doc/lsst.verify/index.rst, python/lsst/verify/__init__.py, python/lsst/verify/compatibility/__init__.py, python/lsst/verify/compatibility/metricTask.py, python/lsst/verify/compatibility/metricsControllerTask.py, python/lsst/verify/compatibility/testUtils.py, python/lsst/verify/metricTask.py, tests/test_metricsController.py, ups/verify.table
This PR adds prototype implementations of the `MetricTask` and `MetricsControllerTask` classes described by [DMTN-098](https://dmtn-098.lsst.io/v/DM-16017/). The implementation of `MetricsControllerTask` currently relies on a hard-coded copy of `ap.verify.measurements.profiling.TimingMetricTask` (see lsst/ap_verify#55 for the "real" version). Its removal is ticketed as [DM-16535](https://jira.lsstcorp.org/browse/DM-16535); setting up a proper configuration system for `MetricsControllerTask` was deemed too challenging for an initial prototype.
This PR adds API documentation but no package-level documentation. The current code is not suitable for general use, so I would prefer to defer writing package-level docs until `MetricsControllerTask` is closer to its intended form.
=> DM-16017: Prototype a metrics-handling Task

bin.src/inspect_job.py, doc/lsst.verify/index.rst, doc/lsst.verify/inspect_job.rst, python/lsst/verify/bin/inspectjob.py, python/lsst/verify/blob.py, python/lsst/verify/compatibility/metricsControllerTask.py, tests/test_inspectjob.py
This PR adds the `inspect_job.py` script for getting a quick and uncluttered summary of a persisted job. User documentation has been added to the Sphinx build.
=> DM-16828: Add Job viewer to lsst.verify

python/lsst/verify/compatibility/__init__.py, python/lsst/verify/compatibility/metadataTask.py, python/lsst/verify/compatibility/metricsControllerTask.py, tests/test_metricsController.py, tests/test_squashMetadataTask.py
This PR factors out the SQuaSH-specific metadata keys applied by `MetricsControllerTask.runDataRefs` into a subtask, so that they can be easily replaced if the need arises. Aside from documenting the new config field in `MetricsControllerConfig`, I have not added any "user guide" documentation, as this is not a config option that most users need to be aware of.
=> DM-16642: Generalize job metadata code

doc/lsst.verify/index.rst, doc/lsst.verify/tasks/lsst.verify.compatibility.MetricTask.rst, doc/lsst.verify/tasks/lsst.verify.compatibility.MetricsControllerTask.rst, doc/lsst.verify/tasks/lsst.verify.compatibility.SquashMetadataTask.rst, python/lsst/verify/compatibility/metricRegistry.py, python/lsst/verify/compatibility/metricTask.py, python/lsst/verify/compatibility/metricsControllerTask.py, tests/test_metricRegistry.py, tests/test_metricsController.py
This PR adds infrastructure to `lsst.verify.compatibility` for configuring `MetricTask`s, and modifies `MetricsControllerTask` to use it. Since this change makes `MetricsControllerTask` usable outside of carefully controlled environments, this PR also adds task documentation for `MetricTask` and `MetricsControllerTask`.
=> DM-16535: Implement MetricRegistry

doc/index.rst, doc/lsst.verify/index.rst, doc/lsst.verify/tasks/lsst.verify.gen2tasks.MetricTask.rst, doc/lsst.verify/tasks/lsst.verify.gen2tasks.MetricsControllerTask.rst, doc/lsst.verify/tasks/lsst.verify.gen2tasks.SquashMetadataTask.rst, doc/lsst.verify/tasks/lsst.verify.tasks.ConfigPpdbLoader.rst, doc/lsst.verify/tasks/lsst.verify.tasks.MetadataMetricTask.rst, doc/lsst.verify/tasks/lsst.verify.tasks.PpdbMetricTask.rst, python/lsst/verify/__init__.py, python/lsst/verify/gen2tasks/metricRegistry.py, python/lsst/verify/gen2tasks/metricTask.py, python/lsst/verify/gen2tasks/metricsControllerTask.py, python/lsst/verify/gen2tasks/testUtils.py, python/lsst/verify/tasks/__init__.py, python/lsst/verify/tasks/metadataMetricTask.py, python/lsst/verify/tasks/metricTask.py, python/lsst/verify/tasks/ppdbMetricTask.py, python/lsst/verify/tasks/testUtils.py, tests/test_configPpdbLoader.py, tests/test_metricsController.py, ups/verify.table
This PR adds two abstract subclasses of `MetricTask` (`MetadataMetricTask` and `PpdbMetricTask`), along with corresponding documentation. It also fixes a number of bugs and usability issues found while testing DM-16536.
=> DM-16536: Migrate all metrics from ap.verify.measurements

doc/lsst.verify/tasks/lsst.verify.gen2tasks.MetricTask.rst, doc/lsst.verify/tasks/lsst.verify.gen2tasks.MetricsControllerTask.rst, doc/lsst.verify/tasks/lsst.verify.tasks.TimingMetricTask.rst, python/lsst/verify/bin/inspectjob.py, python/lsst/verify/tasks/__init__.py, python/lsst/verify/tasks/commonMetrics.py, tests/test_commonMetrics.py, ups/verify.table
This PR migrates `lsst.ap.verify.measurements.profiling.TimingMetricTask` to `lsst.verify.tasks.commonMetrics.TimingMetricTask`, along with its task topic page and unit tests. It also makes some tweaks to the task documentation.
=> DM-18490: Move TimingMetricTask to verify

python/lsst/verify/gen2tasks/metricsControllerTask.py, tests/test_metricsController.py
This PR lets packages like `ap_verify` and `validate_drp` add their own metadata to jobs created by `MetricsControllerTask` without having to create a custom metadata adder (e.g., a subtask of `SquashMetadataTask`) or modify `verify` code. There isn't any specific metadata that we or DRP need to add at the moment, but this capability may be useful as `verify` gets adopted more broadly.
=> DM-16736: Let MetricsControllerTask store application-specific metadata

python/lsst/verify/yamlutils.py, tests/test_metrics.py
This PR removes all `YAMLLoadWarning`s from building `verify`. I also manually searched for `yaml.load` calls that are not exercised by the unit tests, but didn't find any.
=> DM-18906: Use safe YAML loading in verify

python/lsst/verify/bin/dispatchverify.py
This will keep passwords secret when running from the command line.
****
=> DM -20325: Add interactive option

tests/test_squash.py
The lsst.verify.squash client got updated in DM-13237 but we forgot to check the tests with responses installed, which does finer-grained testing of the HTTP client itself. This updates those tests to better reflect the current client.
Perhaps we should add responses to the stack so that everyone can take advantage of these tests?
=> DM-20957: Update responses-based tests for new squash client

python/lsst/verify/bin/inspectjob.py
This PR fixes a bug that caused `inspect_job.py` to reject all command-line arguments. I've confirmed that the new script is fully functional. I've also tested `dispatch_verify.py` and `lint_metrics.py`, and they work fine as-is.
=> DM-20963: inspect_job.py broken

doc/lsst.verify/tasks/lsst.verify.tasks.MemoryMetricTask.rst, doc/lsst.verify/tasks/lsst.verify.tasks.TimingMetricTask.rst, python/lsst/verify/measurement.py, python/lsst/verify/tasks/commonMetrics.py, tests/test_commonMetrics.py
This PR adds `MemoryMetricTask`, a class for computing the values of the memory metrics introduced in lsst/verify_metrics#18. It also fixes some minor bugs I found in the process.
=> DM-20702: Create memory usage metric

doc/lsst.verify/tasks/lsst.verify.gen2tasks.MetricTask.rst, doc/lsst.verify/tasks/lsst.verify.tasks.MetadataMetricTask.rst, doc/lsst.verify/tasks/lsst.verify.tasks.MultiMetadataMetricTask.rst, python/lsst/verify/gen2tasks/metricTask.py, python/lsst/verify/gen2tasks/metricsControllerTask.py, python/lsst/verify/gen2tasks/testUtils.py, python/lsst/verify/tasks/commonMetrics.py, python/lsst/verify/tasks/metadataMetricTask.py, python/lsst/verify/tasks/ppdbMetricTask.py, python/lsst/verify/tasks/testUtils.py, tests/test_commonMetrics.py, tests/test_metricsController.py
This PR adds a method to `gen2tasks.MetricTask` that lets it specify whether it takes scalar or vector input, and modifies `MetricsControllerTask` to check it. All `MetricTask`s have been converted to take scalar inputs, except for the abstract `MetadataMetricTask`, which has been split into both a scalar and a vector version (`MetadataMetricTask` and `MultiMetadataMetricTask`, respectively).
=> DM-20974: Remove aggregation support/requirement from MetricTask

python/lsst/verify/gen2tasks/metricsControllerTask.py, tests/test_metricsController.py
This PR gives `MetricsControllerTask.run` an optional flag that prevents it from recalculating metrics for data IDs that have already been processed. Because in Gen 2 metrics are loaded and stored as collections (`Job`s), the system isn't foolproof; metrics may be missed if other metrics in the same file did get calculated.
=> DM-22120: ap_verify scales poorly to large runs

python/lsst/verify/tasks/commonMetrics.py
This PR adds a string completion timestamp to the metadata for all timing measurements. There are no test or documentation changes, as measurement metadata are provided "as-is" with no requirements on their availability or format.
Example output from `inspect_jobs.py`:
```
Measurements:
ap_pipe.ApPipeTime =  94.2989 s ({'estimator': 'pipe.base.timeMethod', 'end': '2019-11-16T00:12:02.754711'})
pipe_tasks.ProcessCcdTime =   24.629 s ({'estimator': 'pipe.base.timeMethod', 'end': '2019-11-16T00:10:41.117107'})
ip_isr.IsrTime =   5.3994 s ({'estimator': 'pipe.base.timeMethod', 'end': '2019-11-16T00:10:20.938137'})
pipe_tasks.CharacterizeImageTime =  10.0975 s ({'estimator': 'pipe.base.timeMethod', 'end': '2019-11-16T00:10:31.614739'})
```
=> DM-22093: Store begin/end times of ap_pipe in ap_verify

doc/lsst.verify/tasks/lsst.verify.tasks.ApdbMetricTask.rst, doc/lsst.verify/tasks/lsst.verify.tasks.DirectApdbLoader.rst, python/lsst/verify/tasks/apdbMetricTask.py, python/lsst/verify/tasks/testUtils.py, tests/test_directApdbLoader.py
This PR replaces the default behavior of `PpdbMetricTask` (name change pending; see [DM-22039](https://jira.lsstcorp.org/browse/DM-22039)) from reading a science task config (which is not Gen-3-compatible) to reading the `apdb_marker` dataset introduced in lsst/obs_base#182. This change is *not* backwards compatible, as it forces the input of `PpdbMetricTask` to be vector rather than scalar.
=> DM-21877: Create "marker" Butler dataset for PPDB

python/lsst/verify/__init__.py, python/lsst/verify/blobset.py, python/lsst/verify/measurement.py, python/lsst/verify/yamlpersistance.py, tests/butler_utils.py, tests/test_blob.py, tests/test_blobset.py, tests/test_datum.py, tests/test_measurements.py, ups/verify.table
This PR adds Gen 3 Butler support for `lsst.verify.Measurement`. It must be merged after lsst/daf_butler#209.
While `verify` already has JSON persistence code for most of its types, the persisted form for many types, including `Measurement`, is not self-contained and not suitable for standalone datasets. I adopted YAML as the Gen 3 format because I believed it would be no more work than creating a second, more encapsulated, JSON persistence format. In hindsight this was not the case, as I also had to write YAML code for `Datum` and `Blob`, which already have self-contained JSON representations.
The final commit in this PR adds some code for creating simple Butler repositories to `test_measurements.py`. This code will likely be moved to a more central location in the future, but I would …
=> DM-21875: Add StorageClass and Formatter support necessary to persist lsst.verify.Measurement in Gen3 repos

python/lsst/verify/yamlpersistance.py
This PR fixes a bug in YAML persistence of `Measurement` and `Datum` that appears when quantities' values are returned as Numpy floats rather than Python floats.
=> DM-22389: verify fails with Astropy 4

python/lsst/verify/tasks/commonMetrics.py
This PR moves Task-end timestamps to `measurement.extras`, to keep them from being treated as SQuaSH metadata. It also adds a Task-start timestamp, which was requested on [DM-22093](https://jira.lsstcorp.org/browse/DM-22093) but was not implemented at the time to avoid `inspect_job` clutter.
=> DM-22479: SQuaSH being spammed with timestamps

python/lsst/verify/tasks/apdbMetricTask.py, python/lsst/verify/tasks/metricTask.py, tests/butler_utils.py, tests/test_apdbMetricTask.py
This PR lets `ApdbMetricTask` pass its output data ID from `runQuantum` to `run`, allowing fine-grained database metrics in Gen 3. 
For clarity, the first commit is a direct copy of `MetricTask.runQuantum`, which has some nonstandard processing. I can't change the call to `run` without duplicating the rest of the code. :disappointed:
=> DM-21912: Implement PpdbMetricTask.runQuantum

ups/verify.table
Drops EUPS requests. This old requests library breaks tests when modern `responses` is installed.
=> DM-22788: Use conda requests package

python/lsst/verify/job.py
DM-24741: Make serialized `Job` data more readable
This is a simple, non-API, change that will make the JSON output from `Job.write()` more readable.
This is purely for devs to look at output to spot check for validity.
****
Preview the docs at: Docs are unchanged.
=> Make serialized job more readable

python/lsst/verify/bin/dispatchverify.py, python/lsst/verify/metadata/jenkinsci.py
This environment variable specifies a list of branch names, in the
format used by the Jenkins jobs stack_os_matrix.
=> DM-24438: Support a `refs` environment variable in Jenkins.

python/lsst/verify/tasks/commonMetrics.py, python/lsst/verify/tasks/metadataMetricTask.py, python/lsst/verify/tasks/testUtils.py
This PR fixes several bugs in `MetadataMetricTask` that were discovered while developing `ap_verify`, and makes the task's dimensions configurable to support metadata from a variety of science pipeline tasks.
=> DM-21919: Run ap_verify end-to-end in Gen 3

setup.cfg
pytest-doctestplus started throwing errors when import paths don't match correctly. There are some errors with how bin.src is handled in the unit tests in this scenario. This is the only package that experienced such errors. Adding an extra flag, `--doctest-ignore-import-errors`, keeps the old behavior of pytest-doctestplus
This flag works with pytest-doctestplus 0.6.1 and future versions which are not yet in the stack.
****
=> DM-26671: Ignore import errors for bin.src/bin differences

python/lsst/verify/bin/jobReporter.py
The key used for the job dictionary was allowed to use unsafe characters for a filename.  Use butler utilities to sanitize the key so it is safe to use as the filename to write to disk.
****
=> DM-28958: Allow the butler tools to sanitize file names

python/lsst/verify/tasks/metadataMetricTask.py
This PR fixes a bug in `MetadataMetricTask` that made it difficult to run the task repeatedly on the same run collection.
=> DM-27325: Can't rerun ap_verify on same repository in Gen 3

python/lsst/verify/gen2tasks/metricTask.py
This version is now mandatory.
****
=> DM-29509: Add the version when MetricTask was deprecated

python/lsst/verify/tasks/metadataMetricTask.py, python/lsst/verify/tasks/testUtils.py
This PR fixes some visibility and documentation bugs in `verify.tasks.MetadataMetricTask` and related code.
=> DM-29808: Various fixes to MetadataMetricTask

tests/test_apdbMetricTask.py
This PR fixes some unit tests broken by lsst/pipe_base#182.
=> DM-28668: PipelineTask unit test framework bypasses dimensions checks

python/lsst/verify/bin/dispatchverify.py, python/lsst/verify/metadata/jenkinsci.py, python/lsst/verify/metadata/ldf.py
- Job creation date to add in the Job metadata, if not specified the default behaviour is to use the current datetime.
- Expects a ISO8601 formatted datetime in UTC
****
Preview the docs at: https://pipelines.lsst.io/v/DM-30940
=> [DM-30940] Add the --date-created command line option to dispatch_verify.py

python/lsst/verify/bin/inspectjob.py, tests/test_inspectjob.py
This PR fixes some edge cases in `inspect_job.py`.
=> DM-22136: inspect_job.py crashes on empty Job

python/lsst/verify/gen2tasks/metricsControllerTask.py, python/lsst/verify/tasks/apdbMetricTask.py, python/lsst/verify/tasks/metricTask.py
This PR fixes some deprecation warnings related to the task logger transition. It does not attempt to remove local construction of `lsst.log.Log` objects.
=> Remove deprecated use of lsst.log.

python/lsst/verify/bin/jobReporter.py, tests/test_jobReporter.py
This PR fixes a bug that caused `gen3_to_job.py` to crash on reruns. It also takes the opportunity to do some minor code cleanup.
=> DM-31282: Fetch only last-produced metric in chained collection in gen3_to_job

python/lsst/verify/measurement.py, tests/test_measurements.py
This PR adds a constructor-like implementation of `Measurement.__repr__`. Since the internal state of `Measurement` is not trivially related to its constructor arguments, this requires some on-the-fly conversion.
=> DM-31609: lsst.verify.Measurement needs a useful __repr__()

python/lsst/verify/bin/dispatchverify.py, python/lsst/verify/job.py
=> DM-31631: Log response from the dispatch

python/lsst/verify/measurement.py, tests/test_measurements.py
Represent metric values that are ``np.nan`` (or ``np.inf``) in ``verify`` as ``null`` when serializing a job to a JSON document.  When deserializing a JSON document a metric values that is ``null``  is explicitly converted to ``np.nan``.
=> [DM-31131] lsst.verify outputs non-standard NaN in JSON

python/lsst/verify/tasks/apdbMetricTask.py, tests/test_configApdbLoader.py, tests/test_directApdbLoader.py
Use factory method to make Apdb instance instead of calling Apdb
constructor. Unit tests use SQL-base implementation of Apdb and need
to use correct config class.
****
=> DM-31458: Update verify for changes in APDB API 

python/lsst/verify/bin/dispatchverify.py, python/lsst/verify/squash.py
Now that `lsst` prefix is allowed we can use `__name__` with `logger.getChild`.
****
=> DM-31801: Use python logging with __name__

python/lsst/verify/tasks/metadataMetricTask.py, python/lsst/verify/tasks/testUtils.py, tests/test_metricsController.py
This is now the standard storage class for task metadata.
****
=> DM-33220: Change Task metadata storage class to TaskMetadata

python/lsst/verify/tasks/commonMetrics.py, tests/test_commonMetrics.py
This PR updates the implementation of `MemoryMetricTask` to support both version 0 and version 1 of task metadata.
The proposed solution is specific to `MemoryMetricTask`; centralizing metadata versioning in `MetadataMetricTask` would be difficult to do without breaking API compatibility.
=> DM-33837: MemoryMetricTask does not support new-style metadata

python/lsst/verify/jobmetadata.py, tests/test_job.py, ups/verify.table
=> DM-17409: Change Metadata class to use dict interface for keys, values, items

doc/lsst.verify/tasks/lsst.verify.tasks.MetricTask.rst, python/lsst/verify/tasks/apdbMetricTask.py, python/lsst/verify/tasks/commonMetrics.py, python/lsst/verify/tasks/metadataMetricTask.py, python/lsst/verify/tasks/metricTask.py, python/lsst/verify/tasks/testUtils.py, tests/test_apdbMetricTask.py, tests/test_commonMetrics.py, tests/test_configApdbLoader.py, tests/test_directApdbLoader.py
This PR removes some unused features from `MetricTask`, namely the requirements that subclasses accept `None` input and built-in handling of `MetricComputationError`. These changes significantly simplify subclass code and bring `MetricTask` closer in line with current `PipelineTask` conventions.
=> DM-30869: Modernize MetricTask for better Gen 3 workflow

doc/lsst.verify/tasks/lsst.verify.tasks.CpuTimingMetricTask.rst, doc/lsst.verify/tasks/lsst.verify.tasks.MemoryMetricTask.rst, doc/lsst.verify/tasks/lsst.verify.tasks.MetadataMetricTask.rst, doc/lsst.verify/tasks/lsst.verify.tasks.TimingMetricTask.rst, python/lsst/verify/tasks/commonMetrics.py, tests/test_commonMetrics.py
This PR fixes the implementation of `TimingMetricTask` to return the wall-clock time, as advertised, instead of the CPU time. It creates a new task, `CpuTimingMetricTask`, that preserves the old implementation under a more accurate name.
=> DM-37302: lsst.verify.TimingMetricTask does not return wall-clock time

python/lsst/__init__.py
=> DM-37552: Remove unneeded lsstimport import

python/lsst/verify/bin/jobReporter.py, python/lsst/verify/extract_metricvalues.py
Requires lsst/daf_butler#797
****
=> DM-38210: Use butler.get() rather than deprecated getDirect()

python/lsst/verify/tasks/metadataMetricTask.py
Reverts lsst/verify#111
See breakage discussion in https://lsstc.slack.com/archives/C2JPMCF5X/p1683754340587629
=> Revert "DM-38953: Adopt now-supported approach to dynamic connections."

tests/test_apdbMetricTask.py
=> DM-39605: Use butler.dimensions rather than butler.registry.dimensions

python/lsst/verify/bin/jobReporter.py, python/lsst/verify/extract_metricvalues.py, tests/test_extract_metricvalues.py
=> DM-34340: Adapt to daf_butler API changes.

tests/test_apdbMetricTask.py
This is a reasonable thing to do in general, but is important when using pytest-randomly because when using that plugin without the `--randomly-dont-reset-seed` flag, the seed is forced to the global value before every test is run. This leads to makeTestCollection returning the same random integer for every test and the runs clash in the shared repo.
****
=> DM-41846: Use the test ID as the unique component of the test run collection

tests/test_apdbMetricTask.py
=> DM-40150: Use QuantumContext rather than deprecated ButlerQuantumContext

tests/test_apdbMetricTask.py
In-memory SQLite APDB does not really work since some time already.
****
=> DM-49464: Use on-disk APDB for tests
